version: "3"

services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - order-service
      - driver-service
      - tracking-service
      - dispatch-service
      - notification-service
      - ai-service
      - user-service
      - admin-service
      - chatbot-service
      - payment-service

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    environment:
      DATABASE_URL: postgresql://delivery:delivery@postgres:5432/delivery_db?schema=auth
    container_name: auth-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  order-service:
    build: ./order-service
    env_file:
      - ./order-service/.env
    container_name: order-service
    ports:
      - "3002:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  driver-service:
    build: ./driver-service
    env_file:
      - ./driver-service/.env
    container_name: driver-service
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  tracking-service:
    build: ./tracking-service
    env_file:
      - ./tracking-service/.env
    container_name: tracking-service
    ports:
      - "3004:3000"
    depends_on:
      - redis

  dispatch-service:
    build: ./dispatch-service
    env_file:
      - ./dispatch-service/.env
    container_name: dispatch-service
    ports:
      - "3005:3000"
    depends_on:
      - postgres

  notification-service:
    build: ./notification-service
    env_file:
      - ./notification-service/.env
    container_name: notification-service
    ports:
      - "3006:3000"
    depends_on:
      - rabbitmq

  ai-service:
    build: ./ai-service
    env_file:
      - ./ai-service/.env
    container_name: ai-service
    ports:
      - "3007:3000"

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    environment:
      DATABASE_URL: postgresql://delivery:delivery@postgres:5432/delivery_db?schema=user_profile
    container_name: user-service
    ports:
      - "3008:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  admin-service:
    build: ./admin-service
    env_file:
      - ./admin-service/.env
    container_name: admin-service
    ports:
      - "3009:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  chatbot-service:
    build: ./chatbot-service
    env_file:
      - ./chatbot-service/.env
    container_name: chatbot-service
    ports:
      - "3010:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - ai-service
      - order-service
      - tracking-service
      - driver-service

  payment-service:
    build: ./payment-service
    env_file:
      - ./payment-service/.env
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://delivery:delivery@postgres:5432/delivery_db?schema=payments
    container_name: payment-service
    ports:
      - "3011:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
      POSTGRES_DB: delivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data: