name: CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  CD:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - api-gateway
          - auth-service
          - driver-service
          - order-service
          - tracking-service
          - payment-service
          - notification-service
          - ai-service

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/delivery-${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker push ${{ secrets.DOCKER_USER }}/delivery-${{ matrix.service }}:latest

  all-checks:
    name: CD All Checks Passed
    needs: [CD]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check results
        run: |
          if [ "${{ needs.CD.result }}" != "success" ]; then
            echo " CD failed"
            exit 1
          fi
          echo " CD passed"
